sudo: required
os: linux
language: minimal
addons:
  apt:
    packages:
    - docker-ce
git:
  depth: 4
services:
  - docker

script:
  - docker version
  - travis_wait 15 docker pull lacledeslan/gamesvr-csgo
  - docker build --no-cache --tag lltest/gamesvr-csgo-freeplay --tag lacledeslan/gamesvr-csgo-freeplay --build-arg BUILDNODE=TravisCI -f Dockerfile.linux .
  - docker run -it --rm lltest/gamesvr-csgo-freeplay ./ll-tests/gamesvr-csgo-freeplay.sh

notifications:
  slack:
    secure: ipPaG9sk+wqSDhfnt28NZpPjgr0ksUxdMwEkW1TWkoSTW1ZJ7RWTPTi5CJT21VLtVl54Vvl4BW0C/s5dhRrqmtvVocbls34WUkMCjyhq+joEGErTC3Cu5zTaZTs0pOvbMy5Npqr7nXC3YaY/AV2YOb+X1RTr1dOOIIKVvT/cNRyVomYPq7fjIJvPLAuObZfkszvnRzEX3GtlizQQsuXPEyiZSFnBs3eU2pue0lGXZLbrkvZLB3YkqlrAaZ8T1gcfY8ES49D1d+HsxrB9kxA1sBCzo/Zs40UFWfeo1ntEf7+1IseppebJ6DJSeDYJFfCk37tbGdMqwvrvU0A7ZVwIycTqduPqgYdvJe0MEL8OXu/MM6aTi5Dx+LOLSIfggzRs6Uzi6LJXwDcgskg0R3KMHkMnEiG98OLT+2l/s5AT0mVaareLSMPCh7ByXNH395XbPhDFXyCNhY91/6SG/iFBLZ4RsbpPCGSg/K0CZ/RLQIrqZybtFoGoFittlwfWQBh3/NZW0Yfpsivut5/CAqovWr2dIRXfk6kkWj+nuewcolGt+1OcafV/r0T9Zw0POmAmaAfp+NO49CS9bClc1mfNTo+5rjv3gyYRe078af1Ul8O6+mk3+7+zRemSdhsgIQJYSkCCKMTFacTB6FEMgxc6N+wnrwERNF/4zdjF0VpG8TA=

before_deploy:
  - docker login -u "$DOCKERHUB_USER" -p "$DOCKERHUB_PASS";
deploy:
  provider: script
  script: docker push lacledeslan/gamesvr-csgo-freeplay
  on:
    branch: master
after_deploy:
  - curl -X POST https://hooks.microbadger.com/images/lacledeslan/gamesvr-csgo-freeplay/$MICROBADGER_TOKEN
